export enum Pieces {
    empty = 0,
    pawn,
    rook,
    knight,
    bishop,
    queen,
    king,
    black = 8,
    white = 16,
    all = 0,
}

export const StartingBoard = new Uint8Array([
    Pieces.white | Pieces.rook,
    Pieces.white | Pieces.knight,
    Pieces.white | Pieces.bishop,
    Pieces.white | Pieces.queen,
    Pieces.white | Pieces.king,
    Pieces.white | Pieces.bishop,
    Pieces.white | Pieces.knight,
    Pieces.white | Pieces.rook,
    ...(new Array(8).fill(Pieces.white | Pieces.pawn)),
    ...(new Array(32).fill(Pieces.empty)),
    ...(new Array(8).fill(Pieces.black | Pieces.pawn)),
    Pieces.black | Pieces.rook,
    Pieces.black | Pieces.knight,
    Pieces.black | Pieces.bishop,
    Pieces.black | Pieces.queen,
    Pieces.black | Pieces.king,
    Pieces.black | Pieces.bishop,
    Pieces.black | Pieces.knight,
    Pieces.black | Pieces.rook,
])

export const _StartingBoard = new Uint8Array([
    Pieces.white | Pieces.rook,
    Pieces.empty,
    Pieces.empty,
    Pieces.empty,
    Pieces.white | Pieces.king,
    Pieces.empty,
    Pieces.empty,
    Pieces.white | Pieces.rook,
    ...(new Array(8).fill(Pieces.white | Pieces.pawn)),
    ...(new Array(32).fill(Pieces.empty)),
    ...(new Array(8).fill(Pieces.black | Pieces.pawn)),
    Pieces.black | Pieces.rook,
    Pieces.empty,
    Pieces.empty,
    Pieces.empty,
    Pieces.black | Pieces.king,
    Pieces.empty,
    Pieces.empty,
    Pieces.black | Pieces.rook,
])
