levels = [
    {
        "id": 1,
        "text": [
            "It had been three nights since I left from Phoenixpeak village to search for Valnera Castle and take the Elixir.",
            "I had heard nothing apart from the gargling of Glimbersnatches deep in the forest.",
            "In front of me, I could see one staring at me with glazed eyes and limp limbs.",
            "I raised my stance as it charged towards me, flailing its arms.",
        ],
        "battle": {
            "name": "Glimbersnatch",
            "depth": 1,
            "aggressiveness": 100,
            "positionalPlay": 0,
            "tradeHappy": 50,
            "blindSpots": 50,
        },
    },
    {
        "id": 2,
        "text": [
            "I wiped some of the battle's grime off my left shoulder before carrying on my journey.",
            "After another day of walking and constant rain, my shoes squelched with each step I took.",
            "Through the rainfall, I could see a dimly lit figure under the light of a bridge lantern, arms crossed, with the gushing water of the river behind him.",
            "I approached the man and introduced myself.",
            "[SPEECH:MC]Hello, I am <<<displayname>>> from Phoenixpeak, may I cross the river?",
            "[SPEECH:Bandit]*grunt* Aye. For 100 shards I'll let you pass without harm.",
            "[SPEECH:MC]What! 100 shards",
            "[SPEECH:Bandit]Pay up or I'll take 'em from you kid!",
            "I slowly backed away, but the bandit chased forward.",
        ],
        "battle": {
            "name": "Bandit",
            "depth": 1,
            "aggressiveness": 80,
            "positionalPlay": 80,
            "tradeHappy": 20,
            "blindSpots": 40,
        },
    },
    {
        "id": 3,
        "text": [
            "The bandit yielded and ran away limping into the forest, so I crossed the river over the bridge into Valnera.",
            "Now in enemy territory, I was on high alert, and I jumped at every squirrel and snapped branch.",
            "The night was beginning to draw in, but as I was setting up a fire, I saw the glimmer of a fire-lit torch in the distance.",
            "In the cover of the night, I quickly packed my belongings into my bag and hid behind a tree besides the path.",
            "I held my breath as the Valnera Patrolman paced towards me. He walked over to my dry fire and illuminated the forest with his torch.",
            "Panicking, I moved my foot further behind the tree, snapping a twig under my foot as I placed it down.",
            "The Patrolman spun towards my tree, and I leapt to fight.",
        ],
        "battle": {
            "name": "Valnera Patrolman",
            "depth": 2,
            "aggressiveness": 30,
            "positionalPlay": 90,
            "tradeHappy": 20,
            "blindSpots": 30,
        },
    },
    {
        "id": 4,
        "text": [
            "After a long battle, I disarmed the Patrolman, who scrambled away.",
            "I used his torch to light my fire and rested until sunrise.",
            "I ventured deeper into Valnera, the treetops became denser, and the path thinned until it was barely passable. It wasn't until midday, until the path opened.",
            "I could see the stretch of the Valnera Plains in the distance, but blocking the path was a large figure clutching a wooden club.",
            "I turned towards me with eyes gleaming with malevolence, taking deep guttural breaths.",
            "[SPEECH:MC]Troll - I m-mean no harm, I only seek safe p-passage through the forest!",
            "The troll let out a deep laughter at my nervousness.",
            "[SPEECH:Troll]I hunger for the taste of traveller flesh. Bring yourself to me and I shall feast upon you.",
            "I gulped before steeling myself for battle.",
        ],
        "battle": {
            "name": "Troll",
            "depth": 1,
            "aggressiveness": 100,
            "positionalPlay": 30,
            "tradeHappy": 100,
            "blindSpots": 30,
        },
    },
    {
        "id": 5,
        "text": [
            "The troll's body collapsed into the tree line, and I ran towards the path's end to the Valnera Plains.",
            "I took a deep breath of fresh air and walked towards Valnera Castle.",
            "As I got closer to the castle, the dirt path joined to a well-kept cobbled path which widened to face the front of the castle.",
            "A single guard stood resolute at the castle's gate, protecting the people of Valenera with his immense halberd. I had no quarrel with the people of Valenera, only the emperor and his men.",
            "They were the ones who had kept the Elixir from the entire continent for their own use.",
            "The guard would never let me in alone, so I had to fight him.",
            "[SPEECH:MC]Guard! There's some trouble over here.",
            "I led him to a secluded area near the river bank.",
            "[SPEECH:Guard]What trouble? There's nothing here.",
            "I looked around for anyone watching. Seeing no one, I attacked.",
        ],
        "battle": {
            "name": "Valnera Castle Guard",
            "depth": 1,
            "aggressiveness": 20,
            "positionalPlay": 100,
            "tradeHappy": 30,
            "blindSpots": 20,
        },
    },
    {
        "id": 6,
        "text": [
            "Having the element of surprise, I knocked the guard into the river and quickly ran into the castle, blending into the midday market crowds.",
            "I saw the guard run into the castle and begin searching for me, but he could hardly get through the small alleys and large crowds in full armour.",
            "Swiftly moving towards the keep of the castle, I snuck into the backdoor of the keep used for supplies.",
            "I walked tentatively through the dark halls and down the stairs into a large chamber.",
            "The chamber's walls were covered in biblical tapestries and shelves with strange ingredients and liquids filled the room with a foul smell.",
            "In the middle of the room, a mage was stood low with one hand on the ground, and another on a wooden staff.",
            "[SPEECH:MC]Greetings mage, I am <<<first-letter-of-displayname>>>-",
            "[SPEECH:Mage of Valnera]<<<displayname>>>.",
            "[SPEECH:Mage of Valnera]I know why you have come. You will not take the Elixir from Valnera. I suggest you leave.",
            "[SPEECH:MC]Then we shall fight.",
            "The mage stood up and lifted his staff into the air, and the battle commenced.",
        ],
        "battle": {
            "name": "Mage of Valnera",
            "depth": 2,
            "aggressiveness": 0,
            "positionalPlay": 0,
            "tradeHappy": 50,
            "blindSpots": 15,
        },
    },
    {
        "id": 7,
        "text": [
            "After delivering a striking blow to the mage, his body withered into the air. The hall continued downwards through dark corridors on wet stones.",
            "The hall ended at the side of a gorge. Above me, the ravine continued upwards for as high as I could see, and below me I couldn't see anything; I could only hear a river at the ravine's depths.",
            "The edge I was standing on was connected to the other side with a thin bridge, suspended with ropes from each edge.",
            "On the other side of the bridge, there was a masked fully armoured Elderian guard, holding a great sword in post, defending a metal door.",
            "I slowly crossed the bridge and the Elderian guard crossed towards me.",
            "At the middle of the bridge, a sword's width from each other, I unsheathed my weapon.",
        ],
        "battle": {
            "name": "Elderian Guard",
            "depth": 2,
            "aggressiveness": 40,
            "positionalPlay": 60,
            "tradeHappy": 30,
            "blindSpots": 15,
        },
    },
    {
        "id": 8,
        "text": [
            "I ran between the edge of the bridge and the Elderian guard and faced him with my back towards the door. I fought aggressively against the guard, pushing him towards the hall I came from.",
            "Once I had enough distance, I ran towards the door, with the guard chasing. His heavy amour hindered him so once I crossed it, I used my dagger to cut the rope supports of the bridge.",
            "After catching my breath back, I opened the door.",
            "A rush of hot, sulphurous air engulfed me. I found myself in a massive cavern, with a pedestal at the end, bearing the Elixir.",
            "I ran towards the Elixir, but before I could even get to the centre of the cavern, a colossal creature jumped down from the smoke above.",
            "The Dragon of Valnera.",
        ],
        "battle": {
            "name": "Dragon of Valnera",
            "depth": 3,
            "aggressiveness": 50,
            "positionalPlay": 80,
            "tradeHappy": 40,
            "blindSpots": 10,
        },
    },
    {
        "id": 9,
        "text": [
            "I defeated the Dragon of Valnera. I collected the Elixir from the pedestal, I had the power to rule Valnera, Phoenixpeak, and maybe even the entire continent.",
            "I raised the Elixir high into the sky and smashed it into the floor.",
            "The glass shattered and the Elixir leaked between the gaps in the cobbled floor.",
            "No human should have the power to rule like that. The Elixir had only brought pain, and now it was gone.",
        ],
    },
]
